#166840943 Create role based access control
andela/ah-kifaru-backend pull request #10
Opened 2019-07-02 11:59 UTC by kechyy

#### What does this PR do?
- create role based access control functionality

#### Description of Task to be completed?
- create middleware to verify JWT
- create middleware to authorise user types

#### How should this be manually tested?
- clone the repo
- run npm install
- start server at port 3000
- When a user visit a protected route
- The middleware grant access to all authorised user

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
- [#166840943](https://www.pivotaltracker.com/story/show/166840943)

#### Screenshots (if appropriate)
 N/A

#### Questions:
- N/A

2019-07-05 16:59 UTC, timi-codes requested changes

2019-07-05 16:59 UTC, timi-codes commented on src/middleware/checkers.js
> +class Checkers {
Hello @kechyy, can we have this file renamed?. I think checkers.js is not descriptive enough. Also, appending the folder name to the filename will be nice. Check here for more details. - https://github.com/andela/engineering-playbook/tree/master/5.%20Developing/Conventions#commit-message
I will suggest you use `permission.middleware.js ` or any other name you can think of.

2019-07-05 17:03 UTC, timi-codes reviewed
This looks good! @kechyy however I left some comment below.

2019-07-07 14:18 UTC, Onyimatics approved these changes
Nice work @kechyy. I like your initiative on the test file.

2019-07-10 10:44 UTC, segunolalive requested changes

2019-07-10 10:44 UTC, segunolalive commented on src/middleware/permission.middleware.js
> +  if (role !== 'user' && role !== 'admin' && role !== 'superAdmin') {
```
const {
    token: { role }
  } = req;
```
vs
```
const { role } = req.token;
```

2019-07-10 10:44 UTC, segunolalive commented on src/middleware/permission.middleware.js
> +  if (role !== 'admin' && role !== 'superAdmin') {
switch `negations` to direct comparisons

```
if (role === 'admin' || role === 'superAdmin') {
  return next()
}

return responseGenerator.err(...)
```

2019-07-10 10:44 UTC, segunolalive commented on src/repository/base.repository.js
> +  static async delete(model, options) {
move the `async` modifier to the `controller`

2019-07-10 10:44 UTC, segunolalive commented on src/test/permission.spec.js
> +        expect(res.body).to.have.property('status');
the response body should not have this property

2019-07-10 10:44 UTC, segunolalive commented on src/test/permission.spec.js
> +        expect(res.body).to.have.property('status');
`401` or `403` ?

2019-07-10 10:44 UTC, segunolalive commented on src/test/permission.spec.js
> +        expect(res.body.error).to.equal(
stick to `message` over `error`

2019-07-10 10:44 UTC, segunolalive commented on src/test/permission.spec.js
> +  it('should return 200 when user is an admin or super admin', done => {
The test descriptions don't tell what you're testing, making it impossible to tell their value add

2019-07-15 10:45 UTC, segunolalive requested changes

2019-07-15 10:45 UTC, segunolalive commented on src/test/user.spec.js
> +    expect(userRoleStatus[0].role).to.equal('user');
😍 😍 😍 😍 😍 

I love the logic of this test.

Please remove the superfluous assertions as discussed.

2019-07-15 16:47 UTC, timi-codes approved these changes
Looks good to me

2019-07-15 16:57 UTC, merged