#166840921 Create user profile
andela/ah-kifaru-backend pull request #18
Opened 2019-07-05 05:49 UTC by kechyy

#### What does this PR do?
- Create user profile

#### Description of Task to be completed?
- update user profile route
- generate a test  random jwt token with email to authorise user
- create test to verify the accuracy of the return status code.

#### How should this be manually tested?
- clone the repo
- run npm install
- Hit npm start:dev to start server at port 3000
- Login
- Visit http://localhost:3000/api/v1/auth/user/profile

#### Any background context you want to provide?
- Must login with a valid email address
#### What are the relevant pivotal tracker stories?
[#166840921](https://www.pivotaltracker.com/story/show/166840921)
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2019-07-10 14:18 UTC, tolumide-ng commented on .nyc_output/processinfo/index.json
> +{
Great work @kechyy, could you please remove the .nyc_output folder 
```git rm -rf .nyc_output``` would work

2019-07-10 14:18 UTC, tolumide-ng commented on .src/database/seeders/20190705223532-user.js
> +'use strict';
Hello @kechyy , there seem to be four empty seeders here

2019-07-10 17:04 UTC, segunolalive requested changes

2019-07-10 17:04 UTC, segunolalive commented on src/test/user.spec.js
> +  describe('GET /auth/view/profile/:userId', () => {
Use Restful URL `/users/:id`, i.e `collection/collectionItem`

2019-07-15 09:03 UTC, codexempire commented on src/controllers/user.controller.js
> +  static async updateAccount(req, res) {
Please I think to drive the work of this `function` you could change the name to `updateAccountProfile` so anyone will know what the controller does to the accounts specifically

2019-07-15 09:47 UTC, Onyimatics requested changes
Good job @kechyy. I like the way you implemented your tests.
Please make the changes as suggested.

2019-07-15 09:47 UTC, Onyimatics commented on src/controllers/user.controller.js
> +  static async updateAccount(req, res) {
yea @kechyy, or even `updateProfile`

2019-07-15 10:06 UTC, Onyimatics approved these changes

2019-07-15 14:36 UTC, timi-codes approved these changes
Well done! @kechyy on the test.

2019-07-15 15:00 UTC, merged