Feat report article #166840938
andela/ah-kifaru-backend pull request #21
Opened 2019-07-08 13:31 UTC by olorunwalawrence

#### What does this PR do?
Report an article
#### Description of the task to be completed
- create report article functionality
- validate report
#### How to manually test this PR
- clone the [repo ](https://github.com/andela/ah-kifaru-backend)
- on your terminal, run `git checkout feat-report-article-#166840938`
- create a user model and migration
- create an endpoint to create article
- rebase the create api endpoint with this branch.
- on your terminal, run npm install to install dependencies
- on your terminal, run npm run start:dev to start the application.

#### What is the story identity?

#166840919

2019-07-10 14:44 UTC, Onyimatics reviewed
Well-done @olorunwalawrence . Please don't forget to remove the `.nyc_output` file before pushing again. Thank you.

2019-07-17 05:15 UTC, timi-codes reviewed
Good job so far @olorunwalawrence, I understand that your plan was to finish this feature before rebasing. It's good but I think rebasing now will make your work much easier and faster since we already have some helper functions and models in place.
Here are some of the things I noticed that needs to be worked on
1. I noticed you mistakenly push your .nyc_output before adding it to git ignore. Here is how to fix that
     - Ensure .nyc_output is your gitignore
     - Use this command `git rm -r .nyc_output` to remove the file
     - Force push your changes.
2. You should also avoid escaping eslint rules. Here is a useful code extension for generating jsdocs https://marketplace.visualstudio.com/items?itemName=joelday.docthis
3. There is a response generator available in the helper function for generating responses instead of the jsend dependency you added. It will also be nice to use es6 async-await instead of then catch.

2019-07-17 05:15 UTC, timi-codes commented on .sequelizerc
> +  "config": path.resolve('./src/database/config/config.json'),
I think this will cause some conflicts. Kindly stick to config.js because process.env will not work in a .json file.

2019-07-17 05:15 UTC, timi-codes commented on src/controllers/reportControllers.js
> +import db from '../database/models';
I think this should be placed in an article controller instead of creating a new controller

2019-07-17 05:15 UTC, timi-codes commented on src/controllers/reportControllers.js
> +        return res.status(409).jsend.fail({
Please use the response generator available in the helper function for generating responses. It will also be nice to use es6 async await here.

2019-07-17 05:15 UTC, timi-codes commented on src/controllers/reportControllers.js
> +        status: 201,
Please use the response generator available in the helper function for generating responses. It will also be nice to use es6 async await here.

2019-07-17 05:15 UTC, timi-codes commented on src/controllers/userControllers.js
> +/* eslint-disable require-jsdoc */
You should avoid escaping eslint rules. Here is a useful code extension for generating jsdocs https://marketplace.visualstudio.com/items?itemName=joelday.docthis

2019-07-17 05:15 UTC, timi-codes commented on src/controllers/userControllers.js
> +/* eslint-disable require-jsdoc */
Kindly rebase and use the user.controller.js already available to us

2019-07-19 07:03 UTC, Onyimatics requested changes
Nice work @olorunwalawrence . However, I can see you are yet to implement the changes previously requested. Please kindly do so and also resolve the merge conflicts on your branch. Thank you

2019-07-22 08:58 UTC, closed without merging