#166840930 User Tag Article
andela/ah-kifaru-backend pull request #30
Opened 2019-07-18 06:31 UTC by tobechukwuobitube

#### What does this PR do?
Implement User tag articles

#### Description of Task to be completed?
```
- ensure unit tests are written to test the functionality to be implemented
- ensure that data model for tag articles feature was set up with sequelize
- ensure that user can add tags to the articles they author
- ensure there are validations implemented on the feature
- update swagger documentation for the features implemented
```
#### How should this be manually tested?
The following steps can be used:
1) Clone the repository 
2) Cd into the project folder 
3) Run `npm install` to install all project dependencies. 
4) On the terminal run `npm run start:dev`
5) Make the following http calls on Postman:
        `POST  localhost:3000/api/v1/articles`
        `GET  localhost:3000/api/v1/articles`
        `GET  localhost:3000/api/v1/articles/:articleId`
        `PUT  localhost:3000/api/v1/articles/:articleId`
There is a `tag` element in the corresponding response to the above endpoints respectively as shown in the pictures below.

#### Any background context you want to provide?
- Ensure that `node`, `npm` and `postman` are installed on your machine

#### What are the relevant pivotal tracker stories?
Feature 166840930: https://www.pivotaltracker.com/story/show/166840930

#### Screenshots (if appropriate)
Create Article Endpoint
![image](https://user-images.githubusercontent.com/31288326/61434420-cf6a8d80-a92d-11e9-86e0-7fc07ccdd8b7.png)

Get All Articles Endpoint
![image](https://user-images.githubusercontent.com/31288326/61434447-e6a97b00-a92d-11e9-85e6-e80da2d3c8cb.png)

Update A Specific Article Endpoint
![image](https://user-images.githubusercontent.com/31288326/61434438-ddb8a980-a92d-11e9-9cc1-f94e47140e85.png)

2019-07-19 06:36 UTC, codexempire commented
Nice work @tobechuwku please can you kindly rebase the **PR** so that only implementation for the tags show in file changes.

2019-07-19 07:26 UTC, kechyy requested changes
Good Job @tobechukwuobitube . Please make the few changes I spotted.

2019-07-19 07:26 UTC, kechyy commented on src/repository/base.repository.js
> -  static async findAll(model, options) {
Good Job so far @tobechukwuobitube . However, I noticed the baseRepository findAll method was removed, I think you need to confirm no one else used it before it get merged.

2019-07-19 07:26 UTC, kechyy commented on src/test/article.spec.js
> +const articleEndpoint = '/api/v1/articles';
You may want to remove one end point if you're not using the both. Noticed the are the same route.

2019-07-29 09:55 UTC, kechyy approved these changes

2019-07-29 09:59 UTC, kechyy approved these changes
Good Job @tobechukwuobitube and @codexempire . This looks  good to me.

2019-07-29 10:09 UTC, timi-codes approved these changes
This looks good to me. Good Job @codexempire @tobechukwuobitube

2019-07-29 10:09 UTC, timi-codes commented on src/helpers/tagArticle.js
> +    tags.map(tagName =>
Great implementation @codexempire @tobechukwuobitube

2019-07-29 16:29 UTC, Onyimatics approved these changes
Good job @codexempire and @tobechukwuobitube.
 I like your implementation.

2019-07-29 16:36 UTC, merged