#167374277 User can publish an article
andela/ah-kifaru-backend pull request #34
Opened 2019-07-20 14:29 UTC by codexempire

### What does this PR do?
- Enable **`users`** publish articles

### Description of Tasks to be completed? 
- If an article is saved as draft the article id is passed as the query params if it wants to be published.
- The publish date is set and the updatedAt with the changes.
- If the article is published immediately after writing the publishedDate, createdAt, and updatedAt is set.

### How should this be manually tested?
- Clone the repository
- cd into the project folder
- Run **`npm install`** to install all project dependencies.
- Run **`npm run start:dev`** to start the development server

### Make the following Http `PUT` calls in Postman:
- To publish a drafted article **`localhost:3000/api/v1/articles/publish?articleId={the id of the article}`**
- To publish a new article **`localhost:3000/api/v1/articles/publish`**

#### N.B:- For both requests include the `title`, `description`,`body`, `image i.e (URL)`in the request body

2019-07-23 20:46 UTC, tolumide-ng commented on src/controllers/article.controller.js
>  import BaseRepository from '../repository/base.repository';
Hello, I do not see a `utils` module on this folder... where is this coming from?

2019-07-24 10:44 UTC, timi-codes requested changes
Good Job @codexempire. However, Use the equivalent of isNull dependency provided in Javascript.

2019-07-24 10:44 UTC, timi-codes commented on src/controllers/article.controller.js
> +import { isNull } from 'util';
We can't afford to have util dependencies to check a null value. Please the equivalent of this provided by Javascript.

2019-07-25 08:13 UTC, tohbay approved these changes
Looks good to me.
Well done 👍

2019-07-25 08:24 UTC, kechyy approved these changes
Good Job @codexempire . The test is well detailed.

2019-07-25 08:24 UTC, Onyimatics approved these changes
Good job @codexempire This looks good to me.

2019-07-25 12:55 UTC, segunolalive requested changes
Looking really good. Attend to the comments.

See if there's anything that needs to change. Generally looks ready

2019-07-25 12:55 UTC, segunolalive commented on src/controllers/article.controller.js
> +  static async draftArticle(request, response) {
change title to `createDraft`

2019-07-25 12:55 UTC, segunolalive commented on src/controllers/article.controller.js
> +        publish = await BaseRepository.update(
change `publish` to `publishedArticle`

2019-07-25 12:55 UTC, segunolalive commented on src/controllers/article.controller.js
> +import create from '../helpers/articles';
change `create` to `createArticle`

2019-07-25 15:37 UTC, segunolalive reviewed
Good job, @codexempire .

Make the suggested changes.

2019-07-25 15:37 UTC, segunolalive commented on src/test/article.spec.js
> +    expect(response.body.message).to.equal('articleId must be a number');
You can say `Invalid article id` or to be verbose `Invalid article id. Article id must be a non-zero positive integer`

2019-07-25 15:37 UTC, segunolalive commented on src/test/article.spec.js
> +  it('Returns 400 if the articles image provided not a url', async () => {
... not a `valid` url.

2019-07-25 15:37 UTC, segunolalive commented on src/test/article.spec.js
> +    expect(response.body.message).to.equal('Enter the body of your Article');
A better message would be `A body is required. . . `

2019-07-25 15:37 UTC, segunolalive commented on src/test/article.spec.js
> +  it('Returns 200 if article saved as draft has is been published multiple times and the ublished date is not changing', async () => {
You can change the title to => `Publishing an article multiple times fails silently`

2019-07-25 15:37 UTC, segunolalive commented on src/test/article.spec.js
> +    const articles = await generateArticle({ authorId: firstUser.id });
This is a single article. Keep the variable name singular.

2019-07-25 15:37 UTC, segunolalive commented on src/middleware/validation.schema.js
> +        new Error('Enter a Title for your Article of at least 3 characters')
Title is required

2019-07-25 15:37 UTC, segunolalive commented on src/middleware/validation.schema.js
> +      .error(new Error('Image must contain a valid url')),
Invalid image url

2019-07-25 15:37 UTC, segunolalive commented on src/middleware/validation.schema.js
> +const publishedArticle = {
Add a validation for published date to make sure it's a date string, but don't mark it as required

2019-07-25 20:16 UTC, codexempire commented on src/middleware/validation.schema.js
> +const publishedArticle = {
Thank you but I think the validation would not be necessary since the published date is set by the server

2019-07-25 20:18 UTC, codexempire commented on src/middleware/validation.schema.js
> +      .error(new Error('Image must contain a valid url')),
Thank you, the feedback has been implemented

2019-07-25 20:19 UTC, codexempire commented on src/middleware/validation.schema.js
> +        new Error('Enter a Title for your Article of at least 3 characters')
Thank you, the feedback has been implemented

2019-07-25 20:19 UTC, codexempire commented on src/test/article.spec.js
> +    const articles = await generateArticle({ authorId: firstUser.id });
Thank you, the feedback has been implemented

2019-07-25 20:19 UTC, codexempire commented on src/test/article.spec.js
> +  it('Returns 200 if article saved as draft has is been published multiple times and the ublished date is not changing', async () => {
Thank you, the feedback has been implemented

2019-07-25 20:19 UTC, codexempire commented on src/test/article.spec.js
> +    expect(response.body.message).to.equal('Enter the body of your Article');
Thank you, the feedback has been implemented

2019-07-25 20:19 UTC, codexempire commented on src/test/article.spec.js
> +  it('Returns 400 if the articles image provided not a url', async () => {
Thank you, the feedback has been implemented

2019-07-25 20:19 UTC, codexempire commented on src/test/article.spec.js
> +    expect(response.body.message).to.equal('articleId must be a number');
Thank you, the feedback has been implemented

2019-07-25 21:02 UTC, merged