ft(cmment):article comment
andela/ah-kifaru-backend pull request #39
Opened 2019-07-22 05:08 UTC by olorunwalawrence

#### What does this PR do?
create article comment
#### Description of the task to be completed
- create article comment functionality
- create the endpoint for the article
#### How to manually test this PR
- clone the [repo ](https://github.com/andela/ah-kifaru-backend)
- on your terminal, run ` 166840926-article-comments`
- create a user model and migration
- on your terminal, run npm install to install dependencies
- on your terminal, run npm run start:dev to start the application.

#### What is the story identity?

166840926

2019-07-23 08:08 UTC, timi-codes reviewed
Good job! @olorunwalawrence. Here are a few changes you should make
- I think it will be nice to show how comments are being associated with an article and asserting the content in the comment table in your test.
- Endeavor to document your endpoints.

2019-07-23 08:08 UTC, timi-codes commented on src/test/article.spec.js
> +    expect(res.status).to.equal(201);
There is no way to show this comment was successful. It will be nice to query the comment table to see if it was inserted. That way we are sure a comment was created.

2019-07-23 08:08 UTC, timi-codes commented on src/middleware/comment.validation.js
> +        `Invalid violation. Violation can be ['Discrimination', 'Plagiarism', 'Sexual Content', 'Offensive Language']`
How does this come in place in the comment section? How do you know a comment violates the term and condition.

2019-07-23 08:08 UTC, timi-codes commented on src/test/article.spec.js
> +    expect(res.status).to.equal(400);
Please, you can change to 401 instead and also make the changes to auth.middleware.js as Segun suggested yesterday.

2019-07-23 08:08 UTC, timi-codes commented on src/test/article.spec.js
> +    );
I think it will be nice to show how comments are being associated with an article and asserting the content in the comment table.

2019-07-23 08:08 UTC, timi-codes commented on src/test/article.spec.js
> +    const createdComment = await createComment(
Good job here. Please use the same method to created comment and associate them an article in all the test

2019-07-28 11:51 UTC, olorunwalawrence commented on src/test/article.spec.js
> +    expect(res.status).to.equal(400);
thank you for this

2019-07-29 12:13 UTC, codexempire requested changes
Nice work @olorunwalawrence 👍 

Work on the comments made
Try writing more tests to increase coverage, it dropped from `90` to `87`

2019-07-29 12:13 UTC, codexempire commented on src/test/search.spec.js
> +describe.skip('GET api/v1/search', () => {
Please @olorunwalawrence can you kindly remove the `.skip` after the describe

2019-07-29 12:13 UTC, codexempire commented on src/test/user.spec.js
> +    it.skip('should follow another user', async () => {
Also here remove the `.skip` and wherever you use it within the tests

2019-07-29 12:13 UTC, codexempire commented on src/middleware/validation.schema.js
> +    // get comments
Please remove all comment from your code

2019-07-29 13:22 UTC, olorunwalawrence commented on src/test/search.spec.js
> +describe.skip('GET api/v1/search', () => {
got that

2019-07-30 11:31 UTC, tohbay requested changes
Good work @olorunwalawrence 👍 

Resolve the merge conflicts

2019-07-31 00:12 UTC, timi-codes requested changes
Awesome Job. However, Please remove the Reset password functionality which are not related to the article comment, this way we don't run into conflict when the two PR's are merged.

2019-07-31 00:12 UTC, timi-codes commented on src/controllers/article.controller.js
> +  static async reportArticle(req, res) {
Good job @olorunwalawrence, Can we have this removed since report article is a different PR from article comment

2019-07-31 00:12 UTC, timi-codes commented on src/controllers/comment.controller.js
> +class commentsController {
A class name should start with a capital letter

2019-07-31 00:12 UTC, timi-codes commented on src/database/migrations/20190715211346-create-report.js
> +    queryInterface.createTable('Reports', {
Good job @olorunwalawrence, Can we have this removed since report article is a different PR from article comment

2019-07-31 00:12 UTC, timi-codes commented on src/database/models/Report.js
> +      type: DataTypes.ENUM(
Good job @olorunwalawrence, Can we have this removed since report article is a different PR from article comment

2019-07-31 00:12 UTC, timi-codes commented on src/test/article.spec.js
> +    expect(res.status).to.equal(201);
There is no way to show this comment was successful. It will be nice to query the comment table to see if it was inserted. That way we are sure a comment was created.

2019-07-31 00:12 UTC, timi-codes commented on src/test/article.spec.js
> +    const token = helper.jwtSigner({ id: comenter.id });
I think it will be nice to show how comments are being associated with an article and asserting the content in the comment table.

2019-07-31 00:12 UTC, timi-codes commented on src/test/article.spec.js
> +    expect(res.body.data).to.equal('Comment updated');
Good Job, Please assert the values in the database are what was created. This will give some level of confidence in your test

2019-07-31 00:12 UTC, timi-codes commented on src/test/article.spec.js
> +  it('should update a comment for an article', async () => {
You have this case tested twice. I think you already have this tested in the previous case.

2019-07-31 00:12 UTC, timi-codes commented on src/test/article.spec.js
> +  it('should update a comment for an article', async () => {
You have this case tested twice. I think you already have this tested in the previous case.

2019-07-31 00:12 UTC, timi-codes commented on src/test/user.spec.js
> +describe(' POST /api/v1/auth/reset-password', async () => {
Please remove this test since there is a reset password PR already

2019-08-01 15:47 UTC, Onyimatics requested changes
Good job @olorunwalawrence . However, please check out why your Travis ci is failing and also try and squash your commits. Thank you.

2019-08-03 22:53 UTC, timi-codes requested changes

2019-08-03 22:53 UTC, timi-codes commented on src/controllers/article.controller.js
> +  static async reportArticle(req, res) {
Please remove report article codes from this PR

2019-08-03 22:53 UTC, timi-codes commented on src/controllers/comment.controller.js
> +class commentsController {
A class name should start with a capital letter

2019-08-04 11:42 UTC, olorunwalawrence commented on src/test/article.spec.js
> +    expect(res.status).to.equal(201);
This was done below, asserting that what was in the response body is the same thing that is in the database.

2019-08-04 12:47 UTC, closed without merging