#167323728 user should be able receive in app notifications
andela/ah-kifaru-backend pull request #44
Opened 2019-07-23 08:55 UTC by timi-codes

#### Description
 - Users can get in-app notification on being followed 
 - An Author can get in-app notification when there is a new comment on their article.
 - All followers of an author get a notification when they publish a new article
#### Type of Change

- [x] New feature (Non-breaking change which adds functionality)

- [x]  Bug fix (Non-breaking change which adds functionality)

#### How Has This Been Tested?
  Integration Testing
#### Pivotal Stories
[#167323728](https://www.pivotaltracker.com/story/show/167323728)

2019-07-24 04:48 UTC, kechyy requested changes
Good Job @timi-codes and @codexempire . I think I like the test break down. Was able to understand the implementation from the test. And the test is not dependent on the app. However, I left just a comment you may want to quickly attend to.

````|Well done.

2019-07-24 04:48 UTC, kechyy commented on src/helpers/notifications.js
> +    // TODO: send email notification at this point
Remove this emailNotify condition if not needed.

2019-07-24 15:32 UTC, kechyy approved these changes

2019-07-24 15:34 UTC, tolumide-ng approved these changes
This looks awesome 👍 Good job @timi-codes  and @codexempire

2019-07-25 00:24 UTC, Onyimatics approved these changes
Good work @timi-codes and @codexempire.

2019-07-26 09:29 UTC, segunolalive requested changes
Great job 💪 
Fix the errors. Merge @codexempire's corrections

@tolumide-ng review and merge, if satisfactory.

2019-07-26 09:29 UTC, segunolalive commented on src/test/notification.spec.js
> +      .patch(`/api/v1/notifications/opt`)
I think this should be `api/v1/users/:id/notifications`

2019-07-26 09:29 UTC, segunolalive commented on src/test/notification.spec.js
> +  it('Returns 404 and error message if no notification was found', async () => {
`404` means the route/resource was not found.

2019-07-26 09:29 UTC, segunolalive commented on src/test/notification.spec.js
> +describe('Test notification helper functions', async () => {
```
describe('Notification helper functions', () => {
   describe('CreateInAppNotification', () => {
    it('returns an object of the created notification', () =>{
    . . .
    } ) 
  }
})
```

2019-07-26 09:29 UTC, segunolalive commented on src/controllers/notification.controller.js
> +          return responseGenerator.sendError(
`sendSuccess`

2019-07-27 20:54 UTC, merged